{
 "title": "Neohub",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "zone",
    "label": "Zone",
    "query": "select distinct name from heatingentry"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT created_at as time, temperature as value, name as metric from heatingentry \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, temperature as value, name as metric from heatingentry \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Heating",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "queryText": "SELECT created_at as time, heat_on as value, name as metric from heatingentry \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, heat_on as value, name as metric from heatingentry \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 11, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "queryText": "SELECT created_at as time, low_battery as value, name as metric from heatingentry \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, low_battery as value, name as metric from heatingentry \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Online",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "queryText": "SELECT created_at as time, offline as value, name as metric from heatingentry \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, offline as value, name as metric from heatingentry \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "$zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "zone" },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 1, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time, temperature from heatingentry\nWHERE time >= $__from / 1000 and time < $__to / 1000 and name = '$zone'",
     "rawQueryText": "SELECT created_at as time, temperature from heatingentry\nWHERE time >= $__from / 1000 and time < $__to / 1000 and name = '$zone'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Heating",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "queryText": "SELECT created_at as time, heat_on from heatingentry\nWHERE time >= $__from / 1000 and time < $__to / 1000 and name = '$zone'",
     "rawQueryText": "SELECT created_at as time, heat_on from heatingentry\nWHERE time >= $__from / 1000 and time < $__to / 1000 and name = '$zone'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Online",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "queryText": "SELECT created_at as time, offline from heatingentry\nWHERE time >= $__from / 1000 and time < $__to / 1000 and name = '$zone'",
     "rawQueryText": "SELECT created_at as time, offline from heatingentry\nWHERE time >= $__from / 1000 and time < $__to / 1000 and name = '$zone'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "queryText": "SELECT created_at as time, low_battery from heatingentry\nWHERE time >= $__from / 1000 and time < $__to / 1000 and name = '$zone'",
     "rawQueryText": "SELECT created_at as time, low_battery from heatingentry\nWHERE time >= $__from / 1000 and time < $__to / 1000 and name = '$zone'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}