{
 "title": "Solar",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Scatter Plots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Solar over Azimuth",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT sunposition.created_at as time, pv_power, azimuth from solarentry inner join sunposition on solarentry.created_at/60 = sunposition.created_at/60\nWHERE time >= $__from / 1000 and time < $__to / 1000 ",
     "rawQueryText": "SELECT sunposition.created_at as time, pv_power, azimuth from solarentry inner join sunposition on solarentry.created_at/60 = sunposition.created_at/60\nWHERE time >= $__from / 1000 and time < $__to / 1000 ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Solar over Altitude",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT sunposition.created_at as time, pv_power, altitude from solarentry inner join sunposition on solarentry.created_at/60 = sunposition.created_at/60\nWHERE time >= $__from / 1000 and time < $__to / 1000 ",
     "rawQueryText": "SELECT sunposition.created_at as time, pv_power, altitude from solarentry inner join sunposition on solarentry.created_at/60 = sunposition.created_at/60\nWHERE time >= $__from / 1000 and time < $__to / 1000 ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Power over Cloudcover",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT weather.created_at as time, pv_power, cloud from solarentry inner join weather on solarentry.created_at/60 = weather.created_at/60\nWHERE time >= $__from / 1000 and time < $__to / 1000 and weather.source = \"openweathermap\"",
     "rawQueryText": "SELECT weather.created_at as time, pv_power, cloud from solarentry inner join weather on solarentry.created_at/60 = weather.created_at/60\nWHERE time >= $__from / 1000 and time < $__to / 1000 and weather.source = \"openweathermap\"",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Charge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  battery_charge as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  battery_charge as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  battery_power as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  battery_power as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  battery_temperature as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  battery_temperature as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  battery_voltage as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  battery_voltage as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  battery_current as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  battery_current as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Cycles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  battery_cycles as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  battery_cycles as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Energy Today", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Generated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  today_generated_solar_energy as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  today_generated_solar_energy as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Consumed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  today_consumed_energy as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  today_consumed_energy as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Energy Cumulative",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "queryText": "SELECT created_at as time, today_generated_solar_energy as solar from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, today_generated_solar_energy as solar from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT created_at as time, today_sold_solar_energy as sold from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, today_sold_solar_energy as sold from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT created_at as time, today_bought_grid_energy as bought from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, today_bought_grid_energy as bought from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT created_at as time, today_consumed_energy as consumed from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, today_consumed_energy as consumed from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Bought",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  today_bought_grid_energy as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  today_bought_grid_energy as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Sold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  today_sold_solar_energy as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  today_sold_solar_energy as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Solar",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  pv_power as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  pv_power as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  load_power as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  load_power as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "queryText": "SELECT created_at as time, battery_power as battery from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, battery_power as battery from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT created_at as time, grid_power as grid from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, grid_power as grid from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT created_at as time, pv_power as solar from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, pv_power as solar from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT created_at as time, load_power as load from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, load_power as load from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "PV Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  pv_1_voltage as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  pv_1_voltage as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Grid",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  grid_power as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  grid_power as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  battery_power as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  battery_power as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "PV Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT created_at as time,  pv_1_current as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time,  pv_1_current as value from solarentry\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Weather", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Cloud Cover",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT created_at as time, cloud as cloud, source as metric from weather\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, cloud as cloud, source as metric from weather\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT created_at as time, temperature as value, source as metric from weather \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, temperature as value, source as metric from weather \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Sun Position", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Azimuth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "queryText": "SELECT created_at as time, azimuth as value from sunposition\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, azimuth as value from sunposition\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "queryText": "SELECT created_at as time, altitude as value from sunposition\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT created_at as time, altitude as value from sunposition\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}