---
- name: install grafana
  hosts: raspberrypis
  tasks:
    - name: add key
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
      become: true

    - name: add repo
      ansible.builtin.apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
      become: true

    - name: install
      ansible.builtin.apt:
        name: grafana
        update_cache: yes
        state: present
      become: true

    - name: start and enable grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started
      become: true

    - name: install sqlite plugin
      shell: grafana-cli plugins install frser-sqlite-datasource
      become: true

    - name: install scatter plugin
      shell: grafana-cli plugins install michaeldmoore-scatter-panel
      become: true

    - name: override home directory protection
      copy:
        src: ./grafana/override.conf
        dest: /etc/systemd/system/grafana-server.service.d/
      become: true

    - name: reload systemctl config
      systemd:
        name: daemon_reload
  
    - name: restart grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: restarted
      become: true
    
