---
- name: install prometheus
  hosts: raspberrypis
  tasks:

    - name: Download and unarchive prometheus into temporary location.
      unarchive:
        src: "https://github.com/prometheus/prometheus/releases/download/v2.47.0-rc.0/prometheus-2.47.0-rc.0.linux-armv7.tar.gz"
        dest: /tmp
        remote_src: true
        mode: 0755

    - name: Move prometheus binary into place.
      copy:
        src: "/tmp/prometheus-2.47.0-rc.0.linux-armv7"
        dest: "/opt/prometheus"
        mode: 0755
        remote_src: true
      become: true

    - name: Create prometheus user.
      user:
        name: prometheus
        shell: /sbin/nologin
        state: present
      become: true

    - name: Copy the prometheus systemd unit file.
      template:
        src: ./prometheus/prometheus.service
        dest: /etc/systemd/system/prometheus.service
        mode: 0644
      become: true
 
    - name: Copy the prometheus config file.
      template:
        src: ./prometheus/prometheus.yml
        dest: /opt/prometheus/prometheus.yml
        mode: 0644
      become: true

    - name: Reload systemd daemon if unit file is changed.
      systemd:
        daemon_reload: true
      become: true

    - name: Ensure prometheus is running and enabled at boot.
      service:
        name: prometheus
        state: started
        enabled: true
      become: true
